brokerClusterName=DefaultCluster
brokerName=broker-a
brokerId=0

deleteWhen=04
fileReservedTime=48

brokerRole=ASYNC_MASTER
flushDiskType=ASYNC_FLUSH

# NameServer
namesrvAddr=rocketmq-namesrv:9876

# VERY IMPORTANT
brokerIP1=192.168.5.118

# 自动创建topic
autoCreateTopicEnable=true
