server:
  port: 8080

spring:
  application:
    name: only-test
  profiles:
    active: dev

---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    dynamic:
      primary: master
      strict: false
      datasource:
        master:
          url: jdbc:mysql://localhost:3306/wuyou_test?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false
          username: root
          password: ${WY_DB_PASSWORD}
          driver-class-name: com.mysql.cj.jdbc.Driver
        slave:
          url: jdbc:mysql://localhost:3306/wuyou_test?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false
          username: root
          password: ${WY_DB_PASSWORD}
          driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: localhost
    port: 6379
    password: ${WY_REDIS_PASSWORD}

mybatis-plus:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.wuyou.onlytest.entity
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

llm:
  api:
    api-key: ${WY_LLM_API_KEY}
    model: ${WY_LLM_API_MODEL}
    full-url: ${WY_LLM_API_URL}

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    tags-sorter: alpha
    operations-sorter: alpha
    display-request-duration: true
  show-actuator: false

rocketmq:
  name-server: 127.0.0.1:9876
  producer:
    group: demo-producer-group
    send-message-timeout: 3000
